#!/usr/bin/env node

const MarkPDF = require('./markpdf.js');

const inputFile = process.argv[2];

if (!inputFile) {
  console.error('Usage: markpdf <markdown-file>');
  console.error('Example: markpdf resume.md');
  process.exit(1);
}

const markpdf = new MarkPDF(inputFile);
global.markpdfInstance = markpdf;
markpdf.run();
